spring:
  datasource:
    url: "database"
    username: "username"
    password: "password"

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true

server:
  error:
    include-stacktrace: never

api:
  omdb:
    key: "key"

  rapidapi:
      key: "key"